### ISSUE TITLE
NP on editing terrain

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/terra-test-game#5]
```
SEVERE: Uncaught exception thrown in Thread[main,5,main]
java.lang.NullPointerException
	at com.ritualsoftheold.testgame.utils.Picker.pick(Picker.java:46)
	at com.ritualsoftheold.testgame.TestGame.onAction(TestGame.java:202)
	at com.jme3.input.InputManager.invokeActions(InputManager.java:169)
	at com.jme3.input.InputManager.onMouseButtonEventQueued(InputManager.java:446)
	at com.jme3.input.InputManager.processQueue(InputManager.java:864)
	at com.jme3.input.InputManager.update(InputManager.java:914)
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:725)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:227)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:499)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:581)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:423)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at com.ritualsoftheold.testgame.TestGame.main(TestGame.java:65)
```

**Comment by Pilvinen** [comment]
Seems to be fixed now.
